//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace currencyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureAKScurrency
    {
        public string Instance { get; set; }
        public string Core { get; set; }
        public string Ram { get; set; }
        public string TemporaryStorage { get; set; }
        public string PayAsYouGo { get; set; }
        public string OneYearReserved { get; set; }
        public string ThreeYearReserved { get; set; }
        public string ThreeYearReservedWithAzureHybridBenefit { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Currency { get; set; }
        public string NodeInstance { get; set; }
        public int Id { get; set; }
    }
}
